name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        ZEN_USERNAME: ${{ secrets.TEST_USERNAME }}
        ZEN_PASSWORD: ${{ secrets.TEST_PASSWORD }}

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: egregors/zenmoney-backup/zenb
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io